services:
  frontend:
    image: aimeeannabelle/annabelledocker:latest
    stdin_open: true # docker run -i
    tty: true # docker run -t
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/app"
  backend:
    image: aimeeannabelle/aimeeannabelledocker:latest
    stdin_open: true # docker run -i
    tty: true # docker run -t
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/app"
  db:
    image: aimeeannabelle/aimeedbdocker:latest
    stdin_open: true # docker run -i
    tty: true # docker run -t
    build:
      context: backend
      dockerfile: db.Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
   frontend:
   backend:
   db:
   
